// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDepub7RM1W9NTNMSGWA1qD3679K8z7RA0',
    appId: '1:19880663459:web:b42147958b0d36eb25a216',
    messagingSenderId: '19880663459',
    projectId: 'jonny-68139',
    authDomain: 'jonny-68139.firebaseapp.com',
    storageBucket: 'jonny-68139.firebasestorage.app',
    measurementId: 'G-JLKHPNFG9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYQEb1_BqUHdh7xqSEZdX0in5RIfNfoQk',
    appId: '1:19880663459:android:4f80354a2a48edda25a216',
    messagingSenderId: '19880663459',
    projectId: 'jonny-68139',
    storageBucket: 'jonny-68139.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCalowSemRs8SuBHwUrj5COy_OGLyJp0lM',
    appId: '1:19880663459:ios:44632c2870b91c3f25a216',
    messagingSenderId: '19880663459',
    projectId: 'jonny-68139',
    storageBucket: 'jonny-68139.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCalowSemRs8SuBHwUrj5COy_OGLyJp0lM',
    appId: '1:19880663459:ios:44632c2870b91c3f25a216',
    messagingSenderId: '19880663459',
    projectId: 'jonny-68139',
    storageBucket: 'jonny-68139.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDepub7RM1W9NTNMSGWA1qD3679K8z7RA0',
    appId: '1:19880663459:web:0d6c8e8f77fcb2fc25a216',
    messagingSenderId: '19880663459',
    projectId: 'jonny-68139',
    authDomain: 'jonny-68139.firebaseapp.com',
    storageBucket: 'jonny-68139.firebasestorage.app',
    measurementId: 'G-SNHPVPS29C',
  );
}
